### ISSUE TITLE
Multi token pair automatic routing swap function

### ISSUE THREAD

**Issue by element2050** [Elements-Studio/interface#2]
分几种情况：
1）例如要交易Token-M -> Token-N，但系统中只有[Token-M,Token-T]和[Token-T,Token-N]交易对，支持自动交易对路由完成Swap；
2）还是交易Token-M -> Token-N，系统中存在多种交易对路由，由于各交易对汇率的差异，寻找一种最优交易路径，
  2.1）直接交易对Token-M -> Token-N可以获得c1个Token-N；
  2.2）交易路径为Token-M -> Token-T -> Token-N ，可以获得c2个Token-N；
若c1>c2，则路径2.1是最优路径。

约束
其中，限制深度不超过3。

需要API返回平台运营的token list，出于安全性考虑，搜索路劲仅限于这个tokenlist，否则会有中间态交易到空气币风险。

**Comment by montecristo43420** [comment]
fixed in [v0.7.4](https://github.com/Elements-Studio/interface/releases/tag/v0.7.4)
