### ISSUE TITLE
Swap页面swap时需判断余额

### ISSUE THREAD

**Issue by element2050** [Elements-Studio/interface#25]
用tokenA swap tokenB时，如果tokenA余额为0，「Swap」按钮置灰，文案提示「insufficient balance」

**Comment by nsnhhuewwr** [comment]
![image](https://user-images.githubusercontent.com/104535172/182506434-8eed3749-dfad-4802-9fac-105e93b0e263.png)

![image](https://user-images.githubusercontent.com/104535172/182506447-2e3c8729-accd-43e6-8eda-db9a96d3e19f.png)
