### ISSUE TITLE
提醒用户链接钱包的弹出框，把插件安装地址也加上？

### ISSUE THREAD

**Issue by yourmoonlight** [Elements-Studio/interface#26]
<img width="448" alt="image" src="https://user-images.githubusercontent.com/6244271/181217554-5143822d-74c0-47fa-8764-50412b8eff7b.png">

**Comment by montecristo43420** [comment]
<img width="548" alt="image" src="https://user-images.githubusercontent.com/91496148/181672917-2255e37b-88cb-4402-b090-a7268555e6ff.png">
