### ISSUE TITLE
Unstake的确认弹窗，没有检查用户的输入和余额

### ISSUE THREAD

**Issue by montecristo43420** [Elements-Studio/interface#27]
如果余额只有0.3，但是用户输入1，还是可以点击Confirm，但是合约执行会fail.
应该在前端输入之后，点击确认的时候判断

**Comment by nsnhhuewwr** [comment]
fix: https://github.com/Elements-Studio/interface/commit/34677b51efef2dd0089216d4c9858a562c3a8344

**Comment by nsnhhuewwr** [comment]
![image](https://user-images.githubusercontent.com/104535172/182528255-d24c20d1-a935-4fce-a13f-f871d2966e81.png)
![image](https://user-images.githubusercontent.com/104535172/182528278-4f325ac8-2ea4-450e-b9c3-bacf7f79bff0.png)
![image](https://user-images.githubusercontent.com/104535172/182528296-b9853239-15b1-44e5-91df-13a1ffa11842.png)
![image](https://user-images.githubusercontent.com/104535172/182528308-516ee712-e43b-4833-82f3-e1afc629e3c2.png)
